name = "capsai"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

# Usage-quota counters
[[kv_namespaces]]
binding = "USAGE_KV"
id = "459b931e4fb640789b8ddfd851fd3510"
