/**
 * A file generated by the AI Adviser, pending user review.
 * Tied to a specific project.
 */
export interface AIGeneratedFile {
  id: string;
  projectId: string;
  title: string;
  description: string;
  content: string;
  language: string;        // syntax highlighting hint: "typescript", "python", "markdown", etc.
  fileType: "code" | "documentation" | "research" | "other";
  suggestedPath?: string;  // e.g. "src/components/Button.tsx", "docs/architecture.md"
  status: "pending" | "accepted" | "rejected";
  createdAt: string;
  createdByMessageId: string; // link back to the chat message that generated it
}

/** Payload for creating a new AI-generated file from the chat. */
export interface CreateAIGeneratedFileInput {
  projectId: string;
  title: string;
  description: string;
  content: string;
  language: string;
  fileType: "code" | "documentation" | "research" | "other";
  suggestedPath?: string;
  createdByMessageId: string;
}